import { createClient } from "@/lib/supabase/server";

export default async function AdminOutboxPage() {
  const supabase = await createClient();
  const { data: rows } = await supabase
    .from("email_outbox")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(100);

  const resendConfigured = !!process.env.RESEND_API_KEY;

  return (
    <div>
      <h1 className="mb-1 text-2xl font-bold tracking-tight" style={{ color: "var(--text)" }}>
        Email Outbox
      </h1>
      <p className="mb-3 text-sm" style={{ color: "var(--muted)" }}>
        Last 100 outbound notifications generated by the platform.
      </p>
      <div
        className="mb-6 rounded-lg p-3 text-xs"
        style={{
          background: resendConfigured
            ? "color-mix(in srgb, var(--green) 8%, transparent)"
            : "color-mix(in srgb, var(--orange) 8%, transparent)",
          color: resendConfigured ? "var(--green)" : "var(--orange)",
          border: `1px solid ${
            resendConfigured ? "var(--green)" : "var(--orange)"
          }`,
          fontFamily: "var(--font-mono)",
        }}
      >
        {resendConfigured
          ? "RESEND_API_KEY detected — emails are sent inline."
          : "RESEND_API_KEY not configured — emails are queued only. Set RESEND_API_KEY (and CAGE_EMAIL_FROM, CAGE_ADMIN_EMAIL) in the environment to enable delivery."}
      </div>
      {(rows ?? []).length === 0 ? (
        <p className="card p-8 text-center text-sm" style={{ color: "var(--muted)" }}>
          No notifications yet.
        </p>
      ) : (
        <div className="space-y-2">
          {(rows ?? []).map((r) => (
            <div key={r.id as string} className="card p-4">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div>
                  <div className="text-sm font-semibold" style={{ color: "var(--text)" }}>
                    {r.subject as string}
                  </div>
                  <div className="text-xs" style={{ color: "var(--muted)" }}>
                    To {r.to_address as string} · kind {r.related_kind as string} ·{" "}
                    {new Date(r.created_at as string).toLocaleString("en-GB")}
                  </div>
                </div>
                <span
                  className={`badge ${
                    r.status === "sent"
                      ? "badge-green"
                      : r.status === "failed"
                      ? "badge-red"
                      : r.status === "skipped"
                      ? "badge-gray"
                      : "badge-orange"
                  }`}
                >
                  {r.status as string}
                </span>
              </div>
              {r.last_error ? (
                <p className="mt-2 text-xs" style={{ color: "var(--red)" }}>
                  {r.last_error as string}
                </p>
              ) : null}
              <pre
                className="mt-2 max-h-32 overflow-y-auto whitespace-pre-wrap rounded p-2 text-xs"
                style={{ background: "var(--surface)", color: "var(--muted2)" }}
              >
                {r.body_text as string}
              </pre>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
